# Generated by Django 4.0.6 on 2022-08-03 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_todolist_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='user_id',
            new_name='user',
        ),
    ]
