# Generated by Django 4.0.6 on 2022-08-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_user_id_todolist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='target_date',
            field=models.DateField(null=True),
        ),
    ]
